// packages/create-app/templates/vue/src/components/Layout.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import Navigation from "./Navigation.vue";

const { currentPath = "/", onAction } = defineProps<{
  currentPath?: string;
  onAction?: (action: Action) => void;
}>();
</script>

<template>
  <div>
    <Navigation :current-path="currentPath" :on-action="onAction" />
    <main style="padding: 1rem">
      <slot />
    </main>
  </div>
</template>

// packages/create-app/templates/svelte/src/components/Layout.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import Navigation from "./Navigation.svelte";

	let {
		children,
		currentPath = "/",
	}: {
		children: Snippet;
		currentPath?: string;
	} = $props();
</script>

<div>
	<Navigation {currentPath} />
	<main style="padding: 1rem">
		{@render children()}
	</main>
</div>
