// packages/create-app/templates/vue/src/pages/ProductDetail.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import { NAV_ACTIONS } from "../actions";
import type { ProductPage } from "../lib/models/product";

const { page, onAction } = defineProps<{
  page: ProductPage;
  onAction?: (action: Action) => void;
}>();

function handleBack(e: MouseEvent) {
  if (onAction) {
    e.preventDefault();
    onAction(NAV_ACTIONS.home);
  }
}
</script>

<template>
  <div>
    <a href="/" @click="handleBack">← Back</a>
    <h1>{{ page.product.name }}</h1>
    <p class="price">${{ page.product.price.toFixed(2) }}</p>
    <p>{{ page.product.description }}</p>
  </div>
</template>

<style scoped>
.price {
  font-size: 1.5rem;
  color: #007bff;
  font-weight: bold;
}
</style>

// packages/create-app/templates/svelte/src/pages/ProductDetail.svelte
<script lang="ts">
	import { NAV_ACTIONS } from "../actions";
	import { getPerform } from "../lib/framework-svelte";
	import type { ProductPage } from "../lib/models/product";

	let { page }: { page: ProductPage } = $props();

	const perform = getPerform();
</script>

<div>
	<a
		href="/"
		onclick={(e) => {
			if (perform) {
				e.preventDefault();
				void perform(NAV_ACTIONS.home);
			}
		}}>← Back</a
	>
	<h1>{page.product.name}</h1>
	<p class="price">${page.product.price.toFixed(2)}</p>
	<p>{page.product.description}</p>
</div>

<style>
	.price {
		font-size: 1.5rem;
		color: #007bff;
		font-weight: bold;
	}
</style>
