// packages/create-app/templates/react-minimal/src/App.tsx
import type { Action, BasePage } from "@finesoft/front";

interface AppProps {
  page?: BasePage | null;
  loading?: boolean;
  onAction?: (action: Action) => void;
}

export default function App({ page, loading = false }: AppProps) {
  if (loading)
    return <main style={{ padding: "2rem", textAlign: "center", color: "#999" }}>Loading…</main>;
  if (!page) return null;

  return (
    <main style={{ padding: "1rem" }}>
      <h1>{page.title}</h1>
      <p>{page.description}</p>
    </main>
  );
}

// packages/create-app/templates/vue-minimal/src/App.vue
<script setup lang="ts">
import type { Action, BasePage } from "@finesoft/front";
import { computed } from "vue";
import Home from "./pages/Home.vue";

const { state, page: ssrPage } = defineProps<{
  state?: { page: BasePage | null; loading: boolean };
  page?: BasePage;
  onAction?: (action: Action) => void;
}>();

const currentPage = computed(() => state?.page ?? ssrPage ?? null);
const loading = computed(() => state?.loading ?? false);
</script>

<template>
  <main style="padding: 1rem">
    <p v-if="loading" style="text-align: center; color: #999">Loading…</p>
    <Home v-else-if="currentPage" :page="currentPage" />
  </main>
</template>
