// templates/vue/src/components/Layout.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front/web";
import Navigation from "./Navigation.vue";

const { currentPath = "/", onAction } = defineProps<{
    currentPath?: string;
    onAction?: (action: Action) => void;
}>();
</script>

<template>
    <div class="app-shell">
        <Navigation :current-path="currentPath" :on-action="onAction" />
        <main class="app-main">
            <slot />
        </main>
    </div>
</template>

// templates/svelte/src/components/Layout.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { Action } from "@finesoft/front/web";
	import Navigation from "./Navigation.svelte";

	let {
		children,
		currentPath = "/",
		onAction,
	}: {
		children: Snippet;
		currentPath?: string;
		onAction?: (action: Action) => void;
	} = $props();
</script>

<div class="app-shell">
	<Navigation {currentPath} {onAction} />
	<main class="app-main">
		{@render children()}
	</main>
</div>
