// templates/react/src/components/Layout.tsx
import type { Action } from "@finesoft/front/web";
import Navigation from "./Navigation";

interface LayoutProps {
    children: React.ReactNode;
    currentPath?: string;
    onAction?: (action: Action) => void;
}

/** 公共布局 — 顶部导航栏 + 内容区 */
export function Layout({ children, currentPath = "/", onAction }: LayoutProps) {
    return (
        <div className="app-shell">
            <Navigation currentPath={currentPath} onAction={onAction} />
            <main className="app-main">{children}</main>
        </div>
    );
}

// templates/svelte/src/components/Layout.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { Action } from "@finesoft/front/web";
	import Navigation from "./Navigation.svelte";

	let {
		children,
		currentPath = "/",
		onAction,
	}: {
		children: Snippet;
		currentPath?: string;
		onAction?: (action: Action) => void;
	} = $props();
</script>

<div class="app-shell">
	<Navigation {currentPath} {onAction} />
	<main class="app-main">
		{@render children()}
	</main>
</div>
