// templates/svelte/src/components/PageRenderer.svelte
<script lang="ts">
	import type { Action } from "@finesoft/front/web";
	import type { AppPage } from "../lib/models/product";
	import About from "../pages/About.svelte";
	import Home from "../pages/Home.svelte";
	import NotFound from "../pages/NotFound.svelte";
	import ProductDetail from "../pages/ProductDetail.svelte";
	import Search from "../pages/Search.svelte";

	let { page, onAction }: { page: AppPage; onAction?: (action: Action) => void } = $props();
</script>

{#if page.pageType === "home"}
	<Home {page} {onAction} />
{:else if page.pageType === "product"}
	<ProductDetail {page} {onAction} />
{:else if page.pageType === "search"}
	<Search {page} {onAction} />
{:else if page.pageType === "about"}
	<About {page} {onAction} />
{:else}
	<NotFound {page} {onAction} />
{/if}

// templates/react/src/components/PageRenderer.tsx
import type { Action } from "@finesoft/front/web";
import type { AppPage } from "../lib/models/product";
import About from "../pages/About";
import Home from "../pages/Home";
import NotFound from "../pages/NotFound";
import ProductDetail from "../pages/ProductDetail";
import Search from "../pages/Search";

interface PageRendererProps {
    page: AppPage;
    onAction?: (action: Action) => void;
}

/** 根据 pageType 分发渲染对应组件 */
export function PageRenderer({ page, onAction }: PageRendererProps) {
    switch (page.pageType) {
        case "home":
            return <Home page={page} onAction={onAction} />;
        case "product":
            return <ProductDetail page={page} onAction={onAction} />;
        case "search":
            return <Search page={page} onAction={onAction} />;
        case "about":
            return <About page={page} onAction={onAction} />;
        case "error":
            return <NotFound page={page} onAction={onAction} />;
    }
}
