// templates/svelte/src/components/ProductCard.svelte
<script lang="ts">
	import type { ProductItem } from "../lib/models/product";

	let { item }: { item: ProductItem } = $props();
</script>

<article class="product-card">
	<h3>{item.name}</h3>
	<p class="price">${item.price.toFixed(2)}</p>
	{#if item.clickAction && "url" in item.clickAction}
		<a
			href={item.clickAction.url}
			>View Details &rarr;</a
		>
	{/if}
</article>

// templates/react/src/components/ProductCard.tsx
import type { ProductItem } from "../lib/models/product";

interface ProductCardProps {
    item: ProductItem;
}

export default function ProductCard({ item }: ProductCardProps) {
    return (
        <article className="product-card">
            <h3>{item.name}</h3>
            <p className="price">${item.price.toFixed(2)}</p>
            {item.clickAction && "url" in item.clickAction && (
                <a href={item.clickAction.url}>View Details &rarr;</a>
            )}
        </article>
    );
}
