// packages/create-app/templates/vue/src/pages/Home.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import ProductCard from "../components/ProductCard.vue";
import type { HomePage } from "../lib/models/product";

const { page, onAction } = defineProps<{ page: HomePage; onAction?: (action: Action) => void }>();
</script>

<template>
  <div>
    <h1>{{ page.title }}</h1>
    <p>{{ page.description }}</p>

    <section v-for="shelf in page.shelves" :key="shelf.id">
      <h2>{{ shelf.title }}</h2>
      <div class="shelf" :class="{ horizontal: shelf.isHorizontal }">
        <ProductCard
          v-for="item in shelf.items"
          :key="item.id"
          :item="item"
          :on-action="onAction"
        />
      </div>
    </section>
  </div>
</template>

<style scoped>
.shelf {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}
.shelf.horizontal {
  flex-wrap: nowrap;
  overflow-x: auto;
}
</style>

// packages/create-app/templates/react/src/pages/Home.tsx
import type { Action } from "@finesoft/front";
import ProductCard from "../components/ProductCard";
import type { HomePage } from "../lib/models/product";

interface HomeProps {
  page: HomePage;
  onAction?: (action: Action) => void;
}

export default function Home({ page, onAction }: HomeProps) {
  return (
    <div>
      <h1>{page.title}</h1>
      <p>{page.description}</p>
      {page.shelves.map((shelf) => (
        <section key={shelf.id}>
          <h2>{shelf.title}</h2>
          <div
            style={{
              display: "flex",
              gap: "1rem",
              flexWrap: shelf.isHorizontal ? "nowrap" : "wrap",
              overflowX: shelf.isHorizontal ? "auto" : undefined,
            }}
          >
            {shelf.items.map((item) => (
              <ProductCard key={item.id} item={item} onAction={onAction} />
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
