// packages/create-app/templates/vue/src/pages/NotFound.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import { NAV_ACTIONS } from "../actions";
import type { ErrorPage } from "../lib/models/product";

const { page, onAction } = defineProps<{ page: ErrorPage; onAction?: (action: Action) => void }>();

function handleHome(e: MouseEvent) {
  if (onAction) {
    e.preventDefault();
    onAction(NAV_ACTIONS.home);
  }
}
</script>

<template>
  <div>
    <h1>{{ page.title }}</h1>
    <p>{{ page.description }}</p>
    <a href="/" @click="handleHome">← Go Home</a>
  </div>
</template>

// packages/create-app/templates/react/src/pages/NotFound.tsx
import type { Action } from "@finesoft/front";
import { makeFlowAction } from "@finesoft/front";
import type { ErrorPage } from "../lib/models/product";

interface NotFoundProps {
  page: ErrorPage;
  onAction?: (action: Action) => void;
}

export default function NotFound({ page, onAction }: NotFoundProps) {
  const handleHome = (e: React.MouseEvent) => {
    e.preventDefault();
    onAction?.(makeFlowAction("/"));
  };

  return (
    <div>
      <h1>{page.title}</h1>
      <p>{page.description}</p>
      <a href="/" onClick={handleHome}>
        ← Go Home
      </a>
    </div>
  );
}
