// templates/svelte/src/App.svelte
<script lang="ts">
	import type { Action } from "@finesoft/front";
	import Layout from "./components/Layout.svelte";
	import Loading from "./components/Loading.svelte";
	import PageRenderer from "./components/PageRenderer.svelte";
	import type { AppPage } from "./lib/models/product";

	let {
		page: ssrPage = null,
		onaction,
	}: { page?: AppPage | null; onaction?: (action: Action) => void } =
		$props();

	let page = $state<AppPage | null>(ssrPage);
	let loading = $state(false);

	export function setPage(newPage: AppPage | null, isLoading: boolean) {
		loading = isLoading;
		if (newPage) page = newPage;
	}
</script>

<Layout currentPath={page?.url ?? "/"} {onaction}>
	{#if loading}
		<Loading />
	{:else if page}
		<PageRenderer {page} {onaction} />
	{/if}
</Layout>

// packages/create-app/templates/react/src/App.tsx
import type { Action } from "@finesoft/front";
import { Layout } from "./components/Layout";
import { Loading } from "./components/Loading";
import { PageRenderer } from "./components/PageRenderer";
import type { AppPage } from "./lib/models/product";

interface AppProps {
  page?: AppPage | null;
  loading?: boolean;
  onAction?: (action: Action) => void;
}

export default function App({ page, loading = false, onAction }: AppProps) {
  return (
    <Layout currentPath={page?.url ?? "/"} onAction={onAction}>
      {loading && <Loading />}
      {page && <PageRenderer page={page} onAction={onAction} />}
    </Layout>
  );
}
