// templates/react/src/pages/Search.tsx
import type { Action } from "@finesoft/front/web";
import ProductCard from "../components/ProductCard";
import type { SearchPage } from "../lib/models/product";

interface SearchProps {
    page: SearchPage;
    onAction?: (action: Action) => void;
}

export default function Search({ page, onAction }: SearchProps) {
    return (
        <section className="page page-search">
            <h1>{page.title}</h1>
            <p>{page.description}</p>
            <div className="results">
                {page.results.map((item) => (
                    <ProductCard key={item.id} item={item} onAction={onAction} />
                ))}
            </div>
            {page.results.length === 0 && <p>No products found.</p>}
        </section>
    );
}

// templates/vue/src/pages/Search.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front/web";
import ProductCard from "../components/ProductCard.vue";
import type { SearchPage } from "../lib/models/product";

const { page, onAction } = defineProps<{ page: SearchPage; onAction?: (action: Action) => void }>();
</script>

<template>
    <section class="page page-search">
        <h1>{{ page.title }}</h1>
        <p>{{ page.description }}</p>

        <div class="results">
            <ProductCard
                v-for="item in page.results"
                :key="item.id"
                :item="item"
                :on-action="onAction"
            />
        </div>

        <p v-if="page.results.length === 0">No products found.</p>
    </section>
</template>
