// packages/create-app/templates/vue/src/pages/About.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import type { AboutPage } from "../lib/models/product";

const { page, onAction: _onAction } = defineProps<{
  page: AboutPage;
  onAction?: (action: Action) => void;
}>();
</script>

<template>
  <div>
    <h1>{{ page.title }}</h1>
    <p>{{ page.content }}</p>
  </div>
</template>

// templates/svelte/src/pages/About.svelte
<script lang="ts">
	import type { Action } from "@finesoft/front";
	import type { AboutPage } from "../lib/models/product";

	let {
		page,
		onaction: _onaction,
	}: { page: AboutPage; onaction?: (action: Action) => void } = $props();
</script>

<div>
	<h1>{page.title}</h1>
	<p>{page.content}</p>
</div>
