// templates/vue/src/pages/Home.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import ProductCard from "../components/ProductCard.vue";
import type { HomePage } from "../lib/models/product";

const { page, onAction } = defineProps<{ page: HomePage; onAction?: (action: Action) => void }>();
</script>

<template>
    <div>
        <h1>{{ page.title }}</h1>
        <p>{{ page.description }}</p>

        <section v-for="shelf in page.shelves" :key="shelf.id">
            <h2>{{ shelf.title }}</h2>
            <div class="shelf" :class="{ horizontal: shelf.isHorizontal }">
                <ProductCard
                    v-for="item in shelf.items"
                    :key="item.id"
                    :item="item"
                    :on-action="onAction"
                />
            </div>
        </section>
    </div>
</template>

<style scoped>
.shelf {
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
}
.shelf.horizontal {
    flex-wrap: nowrap;
    overflow-x: auto;
}
</style>

// templates/svelte/src/pages/Home.svelte
<script lang="ts">
	import type { Action } from "@finesoft/front";
	import ProductCard from "../components/ProductCard.svelte";
	import type { HomePage } from "../lib/models/product";

	let {
		page,
		onaction,
	}: { page: HomePage; onaction?: (action: Action) => void } = $props();
</script>

<div>
	<h1>{page.title}</h1>
	<p>{page.description}</p>

	{#each page.shelves as shelf}
		<section>
			<h2>{shelf.title}</h2>
			<div class="shelf" class:horizontal={shelf.isHorizontal}>
				{#each shelf.items as item}
					<ProductCard {item} {onaction} />
				{/each}
			</div>
		</section>
	{/each}
</div>

<style>
	.shelf {
		display: flex;
		gap: 1rem;
		flex-wrap: wrap;
	}
	.shelf.horizontal {
		flex-wrap: nowrap;
		overflow-x: auto;
	}
</style>
