// packages/create-app/templates/vue/src/pages/NotFound.vue
<script setup lang="ts">
import type { Action } from "@finesoft/front";
import { NAV_ACTIONS } from "../actions";
import type { ErrorPage } from "../lib/models/product";

const { page, onAction } = defineProps<{ page: ErrorPage; onAction?: (action: Action) => void }>();

function handleHome(e: MouseEvent) {
  if (onAction) {
    e.preventDefault();
    onAction(NAV_ACTIONS.home);
  }
}
</script>

<template>
  <div>
    <h1>{{ page.title }}</h1>
    <p>{{ page.description }}</p>
    <a href="/" @click="handleHome">← Go Home</a>
  </div>
</template>

// templates/svelte/src/pages/NotFound.svelte
<script lang="ts">
	import type { Action } from "@finesoft/front";
	import { NAV_ACTIONS } from "../actions";
	import type { ErrorPage } from "../lib/models/product";

	let {
		page,
		onaction,
	}: { page: ErrorPage; onaction?: (action: Action) => void } = $props();
</script>

<div>
	<h1>{page.title}</h1>
	<p>{page.description}</p>
	<a
		href="/"
		onclick={(e) => {
			if (onaction) {
				e.preventDefault();
				onaction(NAV_ACTIONS.home);
			}
		}}>← Go Home</a
	>
</div>
