// templates/svelte/src/App.svelte
<script lang="ts">
    import { untrack } from "svelte";
	import { Outlet, useSnapshot, type WebAppView } from "@finesoft/front/svelte";
	import Layout from "./components/Layout.svelte";
	import { views } from "./views";
	let { app }: { app: WebAppView } = $props();
	const snapshot = untrack(() => useSnapshot(app));
</script>

<Layout currentPath={$snapshot.entries.find((entry) => entry.visible)?.page.url ?? "/"}>
	<Outlet {app} {views} />
</Layout>

// templates/react/src/App.tsx
import { Outlet, useSnapshot, type WebAppView } from "@finesoft/front/react";
import { Layout } from "./components/Layout";
import { views } from "./views";
export default function App({ app }: { readonly app: WebAppView }) {
    const snapshot = useSnapshot(app);
    return (
        <Layout currentPath={snapshot.entries.find((entry) => entry.visible)?.page.url ?? "/"}>
            <Outlet app={app} views={views} />
        </Layout>
    );
}
